R/send_email_out.R
Without quoting the path, the `system()` command will throw an error if the current path contains whitespace characters.
I don't know if this is still relevant considering the [ongoing migration to mailsend-go](https://rich-iannone.github.io/blastula/articles/sending_using_smtp.html), but I thought I'd submit it anyway.
=> shQuote() path to mailsend binary

R/utils-html_manipulation.R, tests/testthat/test-html_manip.R
During gfsub, everything was written to a temp file with
proper UTF-8 encoding; however, when reading from that
temp file, I forgot to tag it as encoding="UTF-8".
=> Fix test breakage on Windows

R/bls_template.R, inst/rmd/template.html
There can be a display issue when the non-breaking space in the left and right `<td>` elements can sometimes undergo conversion. Here is a screenshot that shows that `&nbsp;`s were converted to Â strings:
However, we need these non-breaking spaces (or equivalent characters for both).
The compromise here is to color the space (or its replacement string) the same color as the background. For the inline style that governs the `&nbsp;`, a `color` style rule was added. The color matches the background of the email (i.e., *not* the center, white wrapper). These changes were applied to the `bls_template.R` file and the .Rmd template, so it should apply to emails made by `compose_email()` and those made with R Markdown files and published to Connect.
All tests pass from this change. We do need to …
=> Try to fix display issue where essential non-breaking spaces are converted to text

R/bls_template.R, inst/rmd/template.html
This change makes all images responsive, with a max-width of 100% .
The change was tested in RStudio and a very large external image scaled to 100% of the width of its container.
```r
email <- 
compose_email(
body = md(
"
This is an image with a max-width set (for all media widths)
"
)
)
email
```
Changes were applied to templates for `compose_email()` and for the Connect/Rmd application.
=> Apply CSS rules to the <img> tag

R/add_cta_button.R, R/add_image.R
These changes apply `htmltools::htmlEscape()` on attribute values and text in the `add_cta_button()` and `add_image()` functions. 
Joe, I didn't add any escaping on the `cid` or `uri` values in `add_image()`. Let me know if that really ought to be done and I'll make that change.
=> Use `htmlEscape()` on attrs and text

inst/examples/connect-example-main.Rmd
The `connect-example-main.Rmd` file was mistakenly committed in modified form. This PR restores it back to its working state.
=> Restore Connect example doc to original form

R/connect_email.R
The correction updates the name of the relevant function to the current name of `attach_connect_email()` (and not `connect_email()`). This is in the message shown at the top of an .Rmd email preview window.
=> Correct the function name in the .Rmd email preview 

inst/rmd/template.html
This change corrects the Connect-based email footer. Previously, it had a hard-coded document name and incorrect, misleading information.
=> Make correction to Connect-based email footer

R/smtp_send.R, man/smtp_send.Rd
This fixes a mistake in the documentation for the `smtp_send()` function. The text for the `from` argument has been updated.
=> Make a correction to the `smtp_send()` docs

R/smtp_send.R, man/smtp_send.Rd
To avoid some potential confusion, the example names in the documentation for `smtp_send()` were changed to more relatable names.
=> Modify names used in documentation

DESCRIPTION, NEWS.md, R/create_credentials.R, tests/testthat/test-utils.R
This bugfix release addresses a NOTE and an ERROR that results from not having Pandoc available on the check system (in this case, the CRAN Solaris test machine).
Here is the R CMD check log that this release is meant to address:
```
using R version 3.6.1 Patched (2019-11-20 r77446)
using platform: i386-pc-solaris2.10 (32-bit)
using session charset: UTF-8
using option ‘--no-stop-on-test-error’
checking for file ‘blastula/DESCRIPTION’ ... OK
checking extension type ... Package
this is package ‘blastula’ version ‘0.3.0’
package encoding: UTF-8
checking package namespace information ... OK
checking package dependencies ... OK
checking if this is a source package ... OK
checking if there is a namespace ... OK
checking for executable files ... OK
checking for hidden files and directories ... …
```
=> V0.3.1 rc (release for addressing CRAN errors)

NEWS.md, R/mime.R, tests/testthat/test-mime.R
This was due to line endings being erroneously rewritten during the quoted-printable encoding phase
Fixes #150, #140, #93, #124
Look at an email sent from Blastula, using Outlook on Windows.
=> Fix broken rendering on Outlook

inst/rmd/template.html
This simply replaces a single preposition in template text.
`This message was generated at $rsc-date-time$.` ->  `This message was generated on $rsc-date-time$.`
Fixes: #123
=> Improve grammar in Connect email footer message text

inst/examples/connect-example-email.Rmd, inst/examples/connect-example-main.Rmd
This mainly corrects a typo (`attach_report` -> `attach_output`) but also serves as an opportunity to clean up the text of the .Rmd documents to make things more clear.
Fixes https://github.com/rich-iannone/blastula/issues/175.
=> Modify text in Connect .Rmd example files

tests/manual_tests/internal_message_email.R, tests/manual_tests/new_releases_email.R, tests/manual_tests/newsletter_email.R, tests/manual_tests/pizzaplace_email.R, tests/manual_tests/service_changes_email.R, tests/manual_tests/validation_report_email.R, tests/manual_tests/welcome_email.R
This will restore the appearance of the examples to the layouts that had before the large-scale changes.
Fixes: #185
=> Update email examples

R/retrieve_credentials.R, man/delete_credential_key.Rd
I was missing the param value for the `id` argument in the new `delete_credential_key()` function. This PR adds that and updates the associated .Rd file.
=> Doc completion for `delete_credential_key()`

R/blastula_email_format.R
This is because the code for passing content_width to the template was
in a conditional that checked for the connect footer.
Create an Rmd that includes this yaml:
```
output:
blastula::blastula_email:
content_width: 600px
```
The `content_width` was previously being dropped UNLESS rendered using `render_connect_email`, i.e. simply knitting this template wouldn't include the content_width.
=> content_width was not being respected for all uses of blastula_email

R/retrieve_credentials.R
This specifies the service *and* the username. On Mac, deletion was permissive and didn't require provision of the username. On Linux and on Windows, those fields are required by the specific backends.
=> Fix implementation of creds key deletion

NEWS.md, R/blastula_email_format.R, R/bls_template.R, R/compose_email.R, R/create_credentials.R, R/creds_helpers.R, _pkgdown.yml, man/blastula_email.Rd, man/blastula_template.Rd, man/create_smtp_creds_file.Rd, man/create_smtp_creds_key.Rd, man/credential_helpers.Rd
The new `delete_credential_key()` and `delete_all_credential_keys()` functions need to appear in the pkgdown site. To fix this, the `_pkgdown.yml` file is now modified to include those entries. There are several typo fixes, correcting `STMP -> SMTP` in a few places.
Fixes: https://github.com/rich-iannone/blastula/issues/193
=> Documentation fixes

R/compose_email.R, man/compose_email.Rd
This adds some advice about `content_width` values to the `compose_email()` help article.
=> Add additional documentation about `content_width`

R/add_image.R
This resolves an issue seen in Apple Mail clients where images are set to 100% width.
Fixes: #201
=> Specify width additionally in `style` attr for Apple Mail

tests/testthat/test-mime.R
There have been recent test check errors on CRAN stemming from a recent update to the tzdata package. With that update, legacy timezone symlinks were dropped and now only continent/ocean plus city name are acceptable (along with a few backward links like `"GB"` and `"NZ"`). There are a few tests that use the dropped tz representations and those have been removed here. There are still plenty of remaining tests of the `format_rfc2822_date()` function, whose responsibility is to generate MIME-message compliant date/time strings.
=> Don't test with now-invalid tz names

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml
=> Update GHA workflows to latest from r-lib/actions

R/mime.R
remove argument not used in `sprintf("=?utf-8?B?%s?=", base64enc::base64encode(charToRaw(str)), 0).`
remove
```
Warning in sprintf("=?utf-8?B?%s?=", base64enc::base64encode(charToRaw(str)), :
one argument not used by format '=?utf-8?B?%s?='
```
when email is send
=> Fix warning: one argument not used by format '=?utf-8?B?%s?='
